org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

# Minecraft
mc_version=1.20.1

# Architectury
architectury_plugin_version=3.4-SNAPSHOT
architectury_loom_version=1.6-SNAPSHOT
architectury_version=9.1.12

# Forge
forge_version=47.2.0

# Fabric
fabric_loader_version=0.15.11
fabric_api_version=0.92.0+1.20.1

# Mappings
parchment_mc_version=1.20.1
parchment_version=2023.09.03

# Mixin
mixin_version=0.8.5

# JEI (1.20.1)
jei_version=15.2.0.27

# Curios (Forge, optional)
curios_version=5.3.5+1.20.1

# forge-config-api-port (Fabric)
forge_config_api_port_version=8.0.3

# Mod
mod_name=LostTrinkets
mod_version=20.1.3
mod_id=losttrinkets
mod_group=guivnf.losttrinkets

# Publishing (mod-publish-plugin)
mod_publish_version=1.1.0
curseforge_id=1501594
curseforge_slug=lost-trinkets-renewed
modrinth_id=lost-trinkets-renewed
