architectury {
    common("neoforge", "fabric")
}

dependencies {
    modImplementation "dev.architectury:architectury:${project.architectury_version}"

    compileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}") { transitive false }

    compileOnly("mezz.jei:jei-${project.mc_version}-common-api:${project.jei_version}") { transitive false }

    compileOnly("top.theillusivec4.curios:curios-neoforge:${project.curios_neoforge_version}:api") { transitive false }
}
