modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/guivnf/lost-trinkets/issues"
license="LGPLv3"

[[mods]]
modId="losttrinkets"
version="${version}"
displayName="Lost Trinkets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lost-trinkets"
authors="guivnf"
description='''
70+ Unlockable trinkets with different useful abilities.
'''

[[dependencies.losttrinkets]]
    modId="architectury"
    type="required"
    versionRange="[13.0.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="neoforge"
    type="required"
    versionRange="[${neoForgeVersion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="losttrinkets.mixins.json"

[[mixins]]
config="losttrinkets.neoforge.mixins.json"
